# -*- coding: utf-8 -*-
# JMCL dmgbuild settings
# Generates a macOS DMG with multi-language software license agreement
# and custom visual appearance.
from __future__ import unicode_literals
import os.path

# ---- Input from environment/variables ----
APP_BUNDLE = defines.get('app', '/tmp/JMCL.app')
APP_VERSION = defines.get('version', '1.0.0')
LICENSES_DIR = defines.get('licenses_dir', '/Users/cangcang/Documents/开发/JMCL/licenses')

# ---- Basics ----
format = 'UDZO'
size = None  # auto-size based on content
compression_level = 9  # max compression

# ---- Content ----
files = [APP_BUNDLE]
symlinks = {'Applications': '/Applications'}

# ---- Window appearance ----
# Standard DMG window: 660x400, centered reasonably on screen
window_rect = ((200, 150), (660, 400))
icon_size = 96

# ---- Icon positions ----
# Place app icon on the left, Applications symlink on the right
app_filename = os.path.basename(APP_BUNDLE)
icon_locations = {
    app_filename: (200, 200),
    'Applications': (480, 200),
}

# ---- Background ----
# Generated by generate_dmg_background.py
bg_path = os.path.join(LICENSES_DIR, 'dmg_background.png')
if os.path.exists(bg_path):
    background = bg_path
else:
    background = None  # fallback to default

# ---- License ----
# Read license texts as plain UTF-8 strings.
# macOS SLG format handles Unicode natively via dmgbuild.

license_en_path = os.path.join(LICENSES_DIR, 'license_en.txt')
license_zh_path = os.path.join(LICENSES_DIR, 'license_zh.txt')

with open(license_en_path, 'r', encoding='utf-8') as f:
    en_text = f.read()
with open(license_zh_path, 'r', encoding='utf-8') as f:
    zh_text = f.read()

license = {
    'default-language': 'en_US',
    'licenses': {
        'en_US': en_text,
        'zh_CN': zh_text,
    },
    'buttons': {
        'en_US': (
            'English',
            'Agree',
            'Disagree',
            'Print',
            'Save',
            'If you agree to the terms of this license, press "Agree" to install the software. If you do not agree, press "Disagree".',
        ),
        'zh_CN': (
            '简体中文',
            '同意',
            '不同意',
            '打印',
            '保存',
            '如果您同意本许可条款，请按"同意"安装本软件。如果您不同意，请按"不同意"。',
        ),
    },
}